;; DO NOT EDIT THIS FILE, IT IS GENERATED BY RIBUILD ON EACH BUILD

(%%include-once (ribbit "r4rs"))
(%%include-once (ribbit "r4rs/sys"))
(%%include-once "src/cli/cmd/build.scm")
(%%include-once "src/cli/cmd/init.scm")
(%%include-once "src/cli/cmd/install.scm")
(%%include-once "src/cli/cmd/run.scm")
(%%include-once "src/cli/cmd/test.scm")
(%%include-once "src/cli/utils.scm")
(%%include-once "src/config.scm")
(%%include-once "src/core/deps.scm")
(%%include-once "src/core.scm")
(%%include-once "src/rb.scm")
(%%include-once "src/ribuild.scm")
(%%include-once "src/utils.scm")

(main)
