;; `path/.` can only be opened when `path` is a directory
(define (directory? path)
  (file-exists? (string-append path "/.")))

;; all the `.scm` files below `dir`, including the ones in subdirectories
(define (list-scm-files-rec dir)
  (apply append
         (map (lambda (name)
                (let ((path (string-append dir "/" name)))
                  (cond
                    ((directory? path) (list-scm-files-rec path))
                    ((string-suffix? ".scm" name) (list path))
                    (else '()))))
              (list-dir dir))))

;; "dir/**" expands to all the `.scm` files below `dir`
(define (expand-include lib)
  (cond
    ((not (string? lib)) (list lib))
    ((string=? lib "**") (list-scm-files-rec "."))
    ((string-suffix? "/**" lib)
     (list-scm-files-rec (substring lib 0 (- (string-length lib) 3))))
    (else (list lib))))

(define (strip-dot-slash path)
  (if (string-prefix? "./" path)
    (substring path 2 (string-length path))
    path))

(define (same-path? lib path)
  (and (string? lib)
       (string=? (strip-dot-slash lib) (strip-dot-slash path))))

;; when `entry` is given, it is always the last include (even if a glob matched it)
(define (includes-to-string includes path (entry #f))
  (let* ((libs (apply append (map expand-include includes))))
    (call-with-output-file
      path
      (lambda (port)
        (display ";; DO NOT EDIT THIS FILE, IT IS GENERATED BY RIBUILD ON EACH BUILD\n\n" port)
        (for-each (lambda (lib) (write (list '%%include-once lib) port) (display #\newline port))
                  libs)
        (if entry
          (display (string-append "\n(" (symbol->string entry) ")\n") port))))))
