;; `path/.` can only be opened when `path` is a directory
(define (directory? path)
  (file-exists? (string-append path "/.")))

;; all the `.scm` files below `dir`, including the ones in subdirectories
(define (list-scm-files-rec dir)
  (apply append
         (map (lambda (name)
                (let ((path (string-append dir "/" name)))
                  (cond
                    ((directory? path) (list-scm-files-rec path))
                    ((string-suffix? ".scm" name) (list path))
                    (else '()))))
              (list-dir dir))))

;; "dir/**" expands to all the `.scm` files below `dir`
(define (expand-include lib)
  (cond
    ((not (string? lib)) (list lib))
    ((string=? lib "**") (list-scm-files-rec "."))
    ((string-suffix? "/**" lib)
     (list-scm-files-rec (substring lib 0 (- (string-length lib) 3))))
    (else (list lib))))

(define (strip-dot-slash path)
  (if (string-prefix? "./" path)
    (substring path 2 (string-length path))
    path))

(define (same-path? lib path)
  (and (string? lib)
       (string=? (strip-dot-slash lib) (strip-dot-slash path))))

(define (write-includes includes port (indent ""))
  (for-each (lambda (lib)
              (display indent port)
              (write (list '%%include-once lib) port)
              (newline port))
            (apply append (map expand-include includes))))

;; `targets-includes` is a list of (target-name . includes), those includes
;; are only used when compiling for that target.
;; A symbol `entry` is a procedure called at the end, a string `entry` is a
;; file included at the end (used by scripts).
(define (includes-to-string includes path entry (targets-includes '()))
  (call-with-output-file
    path
    (lambda (port)
      (display ";; DO NOT EDIT THIS FILE, IT IS GENERATED BY RIBUILD ON EACH BUILD\n\n" port)
      (write-includes includes port)
      (if (pair? targets-includes)
        (begin
          (display "\n(cond-expand\n" port)
          (for-each (lambda (target-includes)
                      (display (string-append "  ((host " (car target-includes) ")\n") port)
                      (write-includes (cdr target-includes) port "   ")
                      (display "   #t)\n" port))
                    targets-includes)
          (display "  (else #t))\n" port)))
      (cond
        ((symbol? entry)
         (display (string-append "\n(" (symbol->string entry) ")\n") port))
        ((string? entry)
         (newline port)
         (write-includes (list entry) port))))))

;; generated in the current directory, so that the includes resolve like in a package
(define script-build-file "__ribuild_script__.scm")

;; writes the file compiled for every target, and returns its path
(define (write-entry-file config targets)
  (let* ((entry (car (getv 'entry config)))
         (path (if (symbol? entry)
                 (string-append (symbol->string entry) ".scm")
                 script-build-file))
         (targets-includes
           (filter (lambda (target-includes) (pair? (cdr target-includes)))
                   (map (lambda (target-config)
                          (cons (car target-config) (getv 'includes (cdr target-config) '())))
                        targets))))
    (includes-to-string (getv 'includes config '()) path entry targets-includes)
    path))
