;; `path/.` can only be opened when `path` is a directory
(define (directory? path)
  (file-exists? (string-append path "/.")))

;; all the `.scm` files below `dir`, including the ones in subdirectories
(define (list-scm-files-rec dir)
  (apply append
         (map (lambda (name)
                (let ((path (string-append dir "/" name)))
                  (cond
                    ((directory? path) (list-scm-files-rec path))
                    ((string-suffix? ".scm" name) (list path))
                    (else '()))))
              (list-dir dir))))

;; "dir/**" expands to all the `.scm` files below `dir`
(define (expand-include lib)
  (cond
    ((not (string? lib)) (list lib))
    ((string=? lib "**") (list-scm-files-rec "."))
    ((string-suffix? "/**" lib)
     (list-scm-files-rec (substring lib 0 (- (string-length lib) 3))))
    (else (list lib))))

(define (strip-dot-slash path)
  (if (string-prefix? "./" path)
    (substring path 2 (string-length path))
    path))

(define (same-path? lib path)
  (and (string? lib)
       (string=? (strip-dot-slash lib) (strip-dot-slash path))))

;; keeps the first occurrence of each element
(define (remove-duplicates lst)
  (let loop ((rest lst) (result '()))
    (cond
      ((null? rest) (reverse result))
      ((member (car rest) result) (loop (cdr rest) result))
      (else (loop (cdr rest) (cons (car rest) result))))))

(define (write-includes includes port (indent ""))
  (for-each (lambda (lib)
              (display indent port)
              (write (list '%%include-once lib) port)
              (newline port))
            (remove-duplicates (apply append (map expand-include includes)))))

;; `targets-includes` is a list of (target-name . includes), those includes
;; are only used when compiling for that target.
;; A symbol `entry` is a procedure called at the end, a string `entry` is a
;; file included at the end (used by scripts).
(define (includes-to-string includes path entry (targets-includes '()))
  (call-with-output-file
    path
    (lambda (port)
      (display ";; DO NOT EDIT THIS FILE, IT IS GENERATED BY RIBUILD ON EACH BUILD\n\n" port)
      (write-includes includes port)
      (if (pair? targets-includes)
        (begin
          (display "\n(cond-expand\n" port)
          (for-each (lambda (target-includes)
                      (display (string-append "  ((host " (car target-includes) ")\n") port)
                      (write-includes (cdr target-includes) port "   ")
                      (display "   #t)\n" port))
                    targets-includes)
          (display "  (else #t))\n" port)))
      (cond
        ((symbol? entry)
         (display (string-append "\n(" (symbol->string entry) ")\n") port))
        ((string? entry)
         (newline port)
         (write-includes (list entry) port))))))

;; generated in the current directory, so that the includes resolve like in a package
(define script-build-file "__ribuild_script__.scm")

;; the includes of the dependency `name` (a symbol), found in `deps-dir`, with
;; their paths made relative to the current directory
(define (dependency-includes name deps-dir seen)
  (let* ((dir (string-append deps-dir "/" (symbol->string name)))
         (pkg (string-append dir "/package.scm")))
    (cond
      ;; already included, avoids infinite loops with circular dependencies
      ((member dir seen) '())
      ((not (file-exists? pkg))
       (error (string-append "*** Dependency `" (symbol->string name) "` not found in "
                             dir ", run `rib install` to install it")))
      (else
        (let ((config (process-config (call-with-input-file pkg read))))
          (resolve-includes
            (map (lambda (lib)
                   (if (string? lib)
                     (string-append dir "/" (strip-dot-slash lib))
                     lib))
                 (getv 'includes config '()))
            (string-append dir "/" (car (getv 'dependency-dir config '("lib"))))
            (cons dir seen)))))))

;; replaces the dependency names (symbols) by the includes of those dependencies
(define (resolve-includes includes deps-dir (seen '()))
  (apply append
         (map (lambda (lib)
                (if (symbol? lib)
                  (dependency-includes lib deps-dir seen)
                  (list lib)))
              includes)))

;; writes the file compiled for every target, and returns its path
(define (write-entry-file config targets)
  (let* ((entry (car (getv 'entry config)))
         (path (if (symbol? entry)
                 (string-append (symbol->string entry) ".scm")
                 script-build-file))
         (deps-dir (car (getv 'dependency-dir config '("lib"))))
         (targets-includes
           (filter (lambda (target-includes) (pair? (cdr target-includes)))
                   (map (lambda (target-config)
                          (cons (car target-config)
                                (resolve-includes (getv 'includes (cdr target-config) '()) deps-dir)))
                        targets))))
    (includes-to-string (resolve-includes (getv 'includes config '()) deps-dir)
                        path entry targets-includes)
    path))
